## Activity: Anomaly detection with k-means

You are working for a big international bank. The Credit department is reviewing their offerings and wants to get a better understanding of their current customers. You have been tasked to perform a customer segmentation analysis. You will perform a cluster analysis with k-means to identify groups of similar customers.

Students are expected to:
* Download and load the dataset into Python
* Perform data standardisation if required
* Analyse and define the optimal number of clusters
* Fit k-means with default hyperparameters
* Plot the clusters and their centroids
* Tune hyperparameters and re-train k-means
* Analyse and interpret clusters found

The dataset used has been shared by Dheeru Dua and Casey Graff from the University of California.

It is available here: [https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data-numeric](https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data-numeric)


Dua, D. and Graff, C. (2019). UCI Machine Learning Repository [http://archive.ics.uci.edu/ml]. Irvine, CA: University of California, School of Information and Computer Science.

Notes:
* This dataset is a .dat file format. You can still load the file using **read_csv()** but you will need the specify the right separator characters with the parameter **sep**.
* Even though all the columns in this dataset are integers, most of them are actually categorical variables. The data in these columns are not continuous. Only 2 variables are really numeric. Find and use them for your clustering.

1. Open a new Colab notebook. Import the libraries of pandas, Kmeans, altair and sklearn (KMeans and StandardScaler)

In [0]:
# Put your code here #

2. Assign the link to the dataset to a variable called file_url:

In [0]:
# Put your code here #

3. Load the dataset using read_csv() method from the package pandas and the following parameters:
header=None, sep=’\s\s+’ and prefix=’X’

In [0]:
# Put your code here #

4. Display the first 5 rows of the dataframe:

In [0]:
# Put your code here #

5. Extract the columns X3 and X9 and assign them to a new variable called X:

In [0]:
# Put your code here #

6. Instantiate a StandardScaler object and standardise the data and store the result in a variable called ‘X_scaled’

In [0]:
# Put your code here #

7. Create an empty pandas dataframe called ‘clusters’ and an empty list called ‘inertia’

In [0]:
# Put your code here #

8. Create a new column called ‘cluster_range’ from the ‘clusters’ dataframe and assign a range from 1 to 15:

In [0]:
# Put your code here #

9. Using a for loop, fit a k-means with the number of clusters defined in the column ‘cluster_range’ and extract the relevant inertia value and append it to the ‘inertia’ list:

In [0]:
# Put your code here #

10. Create a new column called ‘cluster_range’ from the ‘clusters’ dataframe and assign it the ‘inertia’ list:

In [0]:
# Put your code here #

11. Print ‘clusters’ dataframe

In [0]:
# Put your code here #

12. Using altair package and mark_line and encode methods, display the elbow plot:

In [0]:
# Put your code here #

13. Looking at the elbow plot, find the optimal number of cluster and save this value into a new variable called clusters_number:

In [0]:
# Put your code here #

14. Fit a k-means++ with this number of clusters, n_init=50 and max_iter=1000

In [0]:
# Put your code here #

15. Use the method predict() from sklearn to get the assigned clusters for all data points saved in X_scaled

In [0]:
# Put your code here #

16. Plot the scatter plot with the package altair

In [0]:
# Put your code here #

Looking at the final plot, we can see k-means++ has grouped the data into 4 different clusters. Cluster 0 corresponds to observations with value of X3 under 45 and X9 between 20 and 40. All the data points with X3 value under 45 and X9 over 40 have been assigned to cluster 2. Observations that have X3 over 45 belong to cluster 1. Finally cluster 4 contains data points very low value of X3 and X9. 
Observations for cluster 0 to 2 are quite spread on the X9 axis and it seems there is a natural lower boundary for X3 of 20 (all data points are over 20). But we got few data points that are lower that this boundary (they all belong to cluster 3). These observations seem to be very different from all the other data points from clusters 0 to 2. We will classify them as anomaly and if this was a real project we would have reported these cases to the Risk department for further investigation.