## Exercise 3: Different initialisation parameters

In this exercise, we will the same data as for Exercise 1 and try different values for the hyperparameters init and n_init and see how they affect the final clustering result.




---


1. Open on a new Colab notebook. Import the required packages (pandas, sklearn, altair)


---

In [0]:
# Put your code here #



---

2. Assign the link to the ATO dataset to a variable called file_url:


---

In [0]:
# Put your code here #



---

3. Load the dataset and select the same columns as in exercise 1 and 2 using read_csv() method from the package pandas.


---

In [0]:
# Put your code here #



---

4. Assign the columns ‘Average total business income’ and ‘Average total business expenses’ to a new variable called X:


---

In [0]:
# Put your code here #



---

5. Fit a k-means with n_init equals to 1 and random init. 



---

In [0]:
# Put your code here #



---

6. Using the predict method from the sklearn package, predict the clustering assignment from the input variable (X) and save the results into a new column called ''cluster3” from the dataframe:


---

In [0]:
# Put your code here #



---

7. Plot the clusters using an interactive scatter plot. First, use Chart() and mark_circle() from the package altair to instantiate a scatter plot graph:


---

In [0]:
# Put your code here #



---

8. Use the encode and interactive methods from Altair to specify the display of the scatter plot and its interactivity options with the following parameters:
*   Provide the name of the column ‘Average total business income’ to the parameter ‘x’ (x-axis),
*   Provide the name of the column ‘Average total business expenses' to the parameter ‘x’ (y-axis),
*   Provide the name of the column ‘cluster3:N' to the parameter ‘color’ (different coloring for each group),
*   Provide the list of column names  'Postcode', 'cluster3', 'Average total business income', 'Average total business expenses' to the parameter ‘tooltip’ (information displayed on the tooltip)


---

In [0]:
# Put your code here #

Expected output:

![Figure 29 - Clustering results with n_init of 1 and init as random](https://docs.google.com/uc?export=download&id=1hxvZbhx7cyo7CeDqzVAFViAxkyIWxoBY)



---

9. Repeat steps 5 to 8 but with different k-means hyperparameters: n_init 10 and random init:


---

In [0]:
# Put your code here #

Expected output:

![Figure 30 - Clustering results with n_init of 10 and init as random](https://docs.google.com/uc?export=download&id=134FWYZVzhRg3SLsDKgZpDj_3QrKnZXTa)

In [0]:
# Put your code here #



---

10. Repeat steps 5 to 8 but with different k-means hyperparameters: n_init 100 and random init:


---

In [0]:
# Put your code here #

Expected output:

![Figure 31 - Clustering results with n_init of 10 and init as random](https://docs.google.com/uc?export=download&id=1NCdtCIQ8O-5DEjb-DA2Dq9ohlurbCXgM)

Great job! You just learned how to tune the 2 main hyperparameters responsible for initialising the k-means clusters. You have seen in this exercise that increasing the number of iterations (n_init) didn’t have much impact on the clustering result for this dataset. In this case, it is better to use a lower value for this hyperparameter as it will speed up the training time. But for a different dataset you may face the case where the results differ drastically depending on the n_init value. In this case, you will have to find a value of n_init that is not too small but not too big. You want to find the sweet spot where the results are not changing much compared to the last result obtained with a different value.